spring.application.name=ECommerceBackend
spring.datasource.url=jdbc:postgresql://ep-square-glade-azl5uljg.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dg7FvkVPoT8M
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

jwt.secret=HB582@@^RJD[AAjfvbkwitgfvcGBI*&^$WFhgvdfi&F#GK)^Vjhdu39271;
jwt.expiration-ms=1800000
logging.level.org.springframework.security=DEBUG
razorpay.key.id=rzp_test_TR9nLfv1lN2x5S
razorpay.key.secret=0xfyCpBawiJ7eJtYOb0UXa5N
admin.secret.code=ADMIN123